const topics=["Alle","Politik","Wissenschaft","Technologie","Gesundheit","Wirtschaft","Klima","Sport","Kultur","Raumfahrt","Energie","Digitales","Mobilität","Finanzen","Bildung","Umwelt","Lifestyle","Reisen","Auto","Gaming","KI"];
const homeTopics=["Top","Alle","Politik","Technologie","Wissenschaft"];
let data=[],topic="Top",interests=JSON.parse(localStorage.getItem("pulseInterests")||"null")||topics.slice(1,7);
const $=s=>document.querySelector(s),news=$("#news"),filters=$("#filters"),status=$("#status"),search=document.createElement("input");
function esc(s=""){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function fmt(d){try{return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(d))}catch{return""}}
function color(t){return ({Politik:"#ff3b30",Wissenschaft:"#34c759",Technologie:"#5856d6",Gesundheit:"#ff2d55",Wirtschaft:"#ff9500",Klima:"#30b0c7",Sport:"#00a67d",Kultur:"#af52de",Raumfahrt:"#007aff"})[t]||"#007aff"}
function filtered(){const q=(document.querySelector("#search")?.value||"").toLowerCase();let list=data.filter(x=>(topic==="Top"||topic==="Alle"||x.topic===topic)&&(!q||(x.title+" "+(x.aiSummary||x.summary||"")+" "+(x.sources||[]).map(s=>s.source).join(" ")).toLowerCase().includes(q)));if(topic==="Top")list=list.slice().sort((a,b)=>(b.sourceCount||b.sources?.length||1)-(a.sourceCount||a.sources?.length||1)||new Date(b.date)-new Date(a.date));return list}
function renderFilters(){filters.innerHTML=homeTopics.map(x=>'<button class="chip '+(topic===x?"active":"")+'" data-topic="'+esc(x)+'">'+esc(x)+'</button>').join("")}
function render(){const list=filtered();status.textContent=data.length?list.length+" Meldungen · letzte 24 Stunden":"News werden geladen …";news.innerHTML=list.length?list.map((x,i)=>{const n=x.sourceCount||x.sources?.length||1;return '<article class="card '+(i===0?"featured":"")+'" data-index="'+i+'"><div class="tag" style="color:'+color(x.topic)+'"><span class="dot"></span>'+esc(x.topic)+'</div><h3>'+esc(x.title)+'</h3><p class="summary">'+esc(x.aiSummary||x.summary||"Keine Kurzfassung verfügbar.")+'</p><div class="meta"><span class="source">'+(n>1?'<span class="coverage multi">'+n+" Quellen</span>":"1 Quelle")+'</span><span>'+esc(x.country||"INT")+" · "+fmt(x.date)+'</span></div>'+(x.sources?.length?'<details class="sources"><summary>Quellen anzeigen · '+x.sources.length+'</summary><div class="source-list">'+x.sources.map(s=>'<a href="'+esc(s.url)+'" target="_blank" rel="noopener"><span>'+esc(s.source)+'</span><span>'+fmt(s.date)+'</span></a>').join("")+'</div></details>':"")+'</article>'}).join(""):'<div class="empty">Für diese Auswahl wurden keine Meldungen gefunden.</div>';document.querySelectorAll("#news .card").forEach(c=>c.onclick=e=>{if(e.target.closest("a,details"))return;openArticle(Number(c.dataset.index))})}
function openArticle(i){const a=filtered()[i];if(!a)return;const n=a.sourceCount||a.sources?.length||1;$("#articleDetail").innerHTML='<div class="tag" style="color:'+color(a.topic)+'"><span class="dot"></span>'+esc(a.topic)+'</div><h2>'+esc(a.title)+'</h2><p class="summary">'+esc(a.aiSummary||a.summary||"Keine Kurzfassung verfügbar.")+'</p><div class="meta"><span class="source">'+(n>1?n+" Quellen zusammengeführt":"1 Quelle")+'</span><span>'+esc(a.country||"INT")+" · "+fmt(a.date)+'</span></div>'+(a.sources?.length?'<div class="sources"><h3>Originalquellen</h3><div class="source-list">'+a.sources.map(s=>'<a href="'+esc(s.url)+'" target="_blank" rel="noopener"><span>'+esc(s.source)+'</span><span>'+fmt(s.date)+'</span></a>').join("")+'</div></div>':"");$("#articleSheet").classList.add("show");$("#overlay").classList.add("show")}
function closeSheets(){$("#sheet").classList.remove("show");$("#articleSheet").classList.remove("show");$("#overlay").classList.remove("show")}
function renderSettings(){$("#interestRows").innerHTML=topics.filter(x=>!homeTopics.includes(x)).map(t=>'<div class="row"><div><label>'+esc(t)+'</label></div><input class="toggle" type="checkbox" data-topic-setting="'+esc(t)+'" '+(interests.includes(t)?"checked":"")+'></div>').join("");document.querySelectorAll("[data-topic-setting]").forEach(x=>x.onchange=()=>{if(x.checked&&!interests.includes(x.dataset.topicSetting))interests.push(x.dataset.topicSetting);if(!x.checked)interests=interests.filter(t=>t!==x.dataset.topicSetting);localStorage.setItem("pulseInterests",JSON.stringify(interests));renderFilters();render()})}
$("#settingsBtn").onclick=()=>{$("#sheet").classList.add("show");$("#overlay").classList.add("show")};
$("#closeBtn").onclick=closeSheets;$("#articleCloseBtn").onclick=closeSheets;$("#overlay").onclick=closeSheets;
filters.onclick=e=>{const b=e.target.closest("[data-topic]");if(b){topic=b.dataset.topic;renderFilters();render()}};
renderSettings();renderFilters();
async function load(){try{const r=await fetch("data/news.json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error();data=await r.json();render()}catch(e){status.textContent="News konnten nicht geladen werden";news.innerHTML='<div class="empty"><strong>News-Feed nicht erreichbar.</strong><br>Bitte später erneut versuchen.</div>'}}
load();setInterval(load,300000);